# Generated by Django 5.1.4 on 2024-12-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('cover_image', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField(default='')),
                ('pages', models.IntegerField(default=1)),
                ('genre', models.CharField(choices=[('S-FI', 'Sci-Fi'), ('ROM', 'Romance'), ('HOR', 'Horror'), ('COM', 'Comedy'), ('THR', 'Thriller'), ('FAN', 'Fantasy'), ('DRM', 'Drama'), ('FIC', 'Fiction'), ('NOV', 'Novel'), ('POE', 'Poetry'), ('ART', 'Art'), ('EVE', 'Eve'), ('HIS', 'History'), ('GEO', 'Geography')], default='S-FI', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
