# Generated by Django 5.1.4 on 2024-12-16 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0002_bookcollection_bookreview_bookstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstore',
            name='books',
        ),
        migrations.RemoveField(
            model_name='bookstore',
            name='location',
        ),
        migrations.RemoveField(
            model_name='bookstore',
            name='name',
        ),
        migrations.AddField(
            model_name='bookstore',
            name='collecton_of_books',
            field=models.ManyToManyField(related_name='stores', to='bookStore.books'),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='store_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='store_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='BookNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination_type', models.CharField(choices=[('NOM1', 'Nomination for best seller'), ('NOM2', 'Nomination for best author'), ('NOM3', 'Nomination for best genre'), ('NOM4', 'Nomination for best story'), ('NOM5', 'Nomination for best character')], default='NOM1', max_length=5)),
                ('nomination_date', models.DateField(default=django.utils.timezone.now)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='bookStore.books')),
            ],
        ),
        migrations.DeleteModel(
            name='BookCollection',
        ),
    ]
