# Generated by Django 5.1.4 on 2024-12-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0004_alter_bookreview_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstore',
            old_name='collecton_of_books',
            new_name='collection_of_books',
        ),
    ]
