# Generated by Django 5.1.4 on 2024-12-11 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('BLT', 'Black Tea'), ('MLT', 'Milk Tea'), ('GLT', 'Green Tea'), ('GNT', 'Ginger Tea'), ('MNT', 'Mint Tea')], default='BLT', max_length=4)),
            ],
        ),
    ]
