# Generated by Django 5.1.4 on 2024-12-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='type',
            field=models.CharField(choices=[('BLT', 'Black Tea'), ('MLT', 'Milk Tea'), ('GLT', 'Green Tea'), ('GNT', 'Ginger Tea'), ('MNT', 'Mint Tea')], default='BLT', max_length=3),
        ),
    ]
